// src/pages/Demo/Demo.tsx
import { useNavigate } from 'react-router-dom'
import './Demo.scss'
interface IProps {
  name: string
}

const Demo: React.FC<IProps> = ({ name }) => {
  const navigate = useNavigate()
  return (
    <div
      className="wrapper"
      onClick={() => {
        navigate('/')
      }}
    >
      {name}组件
    </div>
  )
}

export default Demo

// src/views/Demo.vue
<template>
  <h1 @click="skipHomePage">Demo组件</h1>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useRouter } from "vue-router";
export default defineComponent({
  setup() {
    const router = useRouter();
    const skipHomePage = () => {
      router.push("/");
    };
    return {
      skipHomePage
    };
  }
});
</script>

<style lang="scss" scoped></style>
