// src/pages/Home/Home.tsx
import './Home.scss'
import { useNavigate } from 'react-router-dom'
interface IProps {
  name: string
}
const Home: React.FC<IProps> = ({ name }) => {
  const navigate = useNavigate()
  return (
    <div className="wrapper" onClick={() => navigate('/demo')}>
      {name}组件
    </div>
  )
} 

export default Home

// src/views/Home.vue
<template>
  <h1 @click="skipDemoPage">Home组件</h1>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useRouter } from "vue-router";
export default defineComponent({
  setup() {
    const router = useRouter();
    const skipDemoPage = () => {
      router.push("/demo");
    };
    return {
      skipDemoPage
    };
  }
});
</script>

<style lang="scss" scoped></style>
