// src/pages/Home/Home.tsx
import './Home.scss'
import { useNavigate } from 'react-router-dom'
interface IProps {
  name: string
}
const Home: React.FC<IProps> = ({ name }) => {
  const navigate = useNavigate()
  return (
    <div className="wrapper" onClick={() => navigate('/demo')}>
      {name}组件
    </div>
  )
} 

export default Home

// src/views/Home/Home.vue
<template>
  <div class="wrapper">
    <van-button type="primary" block @click="skipDemoPage">Home组件</van-button>
  </div>
</template>

<script lang="ts" setup>
import { useRouter } from "vue-router";

const router = useRouter();
const skipDemoPage = () => {
  router.push("/demo");
};

</script>

<style lang="scss" scoped>
.wrapper {
  width: 100vw;
  height: $height;
  @include top;
  background: skyblue;
}
</style>
